### ISSUE TITLE
Cambiare status di un item in db

### ISSUE THREAD

**Issue by LucaDario** [NPE-Developers/bringit#1]
Creare metodo in  manageListUseCase che, dato un listId, itemId ed il suo status, modifica l item della lista con l'item passato

**Comment by rmontagnin** [comment]
Esiste già uno usecase simile, che è [ModifyListUseCase](https://github.com/NPE-Developers/bringit/blob/feature-usecases/usecase/ModifyListUseCase.js) che permette di modificare gli oggetti dentro una lista.

Quello che vuoi fare si ottiene così:
```javascript
let myItem = getItemInfoUseCase.getItemInfo(itemId); // Ottieni l'oggetto
myItem.setStatus(myStatus); // Cambia stato, se non esiste il metodo basta farlo
modifyListUseCase.updateItemInsideList(listId, myItem); // Salva l'oggetto nella lista
```

Quello che sarebbe da fare e' emettere un evento ad ogni cambiamento (quindi all'interno di `DatabaseSource`, e non fare query direttamente sui messaggi), magari richiamando successivamente `renderMessage`.
