### ISSUE TITLE
Eliminazione di un item da tutte le liste

### ISSUE THREAD

**Issue by LucaDario** [NPE-Developers/bringit#2]
Creare metodo, in manageListUseCase, che dato un listId, listItem lo elimini in tutte i messaggi che lo contengono

**Comment by rmontagnin** [comment]
Esiste `ModifyListUseCase#removeItemFromList` che prende come input `listId` e un `item` (`ListItem`) che puoi ottenere tramite `GetItemInfoUseCase#getItemInfo`. 

```javascript
myItem = getItemInfoUseCase.getItemInfo(myId); // Ottieni l'oggetto
modifyListUseCase.removeItemFromList(myItem); // Rimuovi l'oggetto
```

Quello che sarebbe da fare e' emettere un evento ad ogni cambiamento (quindi all'interno di `DatabaseSource`, e non fare query direttamente sui messaggi), magari richiamando successivamente `renderMessage`.

**Comment by LucaDario** [comment]
Teoricamente l'evento ad ogni cambiamento, chiamando renderMessage,  esiste già ed é gestito da meteor

**Comment by rmontagnin** [comment]
Sposto la discussione riguardante l'evento su #5
