### ISSUE TITLE
Eliminazione lista

### ISSUE THREAD

**Issue by LucaDario** [NPE-Developers/bringit#3]
Creare metodo, in managaListUseCase, che dato un id di una lista elimini tutti i messaggi che contengono quella lista

**Comment by rmontagnin** [comment]
Esiste `ManageListsUseCase#deleteList` che rimuove una list dal database.

```javascript
manageListsUseCase.deleteList(listId); // Rimuovi la lista
```

Quello che sarebbe da fare e' emettere un evento ad ogni cambiamento (quindi all'interno di `DatabaseSource`, e non fare query direttamente sui messaggi), magari richiamando successivamente `renderMessage`.
