### ISSUE TITLE
Evento di cambiamento da DatabaseSource

### ISSUE THREAD

**Issue by rmontagnin** [NPE-Developers/bringit#5]
Quello che sarebbe da fare e' emettere un evento ad ogni cambiamento (quindi all'interno di `DatabaseSource`, e non fare query direttamente sui messaggi), magari richiamando successivamente `renderMessage`.

**Comment by rmontagnin** [comment]
@LucaDario dicevi che è gestito direttamente da Meteor, ma i miei metodi aggiornano il DB che contiene le liste, non lavora direttamente sui messaggi. Vuoi che sposti tutto affinché lavori con i messaggi anziché con un db separato?

**Comment by LucaDario** [comment]
Eh si... perche le liste sono incapsulate sulla collezzione dei messaggi, se no ci tocca rifare tutto il backend di RC

**Comment by LucaDario** [comment]
E comunque durande renderMessage si ha SOLO accesso all'oggetto message

**Comment by rmontagnin** [comment]
Ok, teoricamente basta cambiare solamente [DatabaseSource](https://github.com/NPE-Developers/bringit/blob/feature-usecases/server/database/DatabaseSource.js) e far sì che la collezione sulla quali operi sua quella di Rocket.chat e non quella che attualmente creo io chiamata lists.

Fatto questo tutto dovrebbe continuare a funzionare senza alcun problema.

@LucaDario riesci per caso a trovare che database e tabella utilizza Rocket.chat?
